spring.application.name=visitor-service


server.port=8006

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://dpg-d95aeji8qa3s73dpkfo0-a.oregon-postgres.render.com:5432/visitor_db_jtzv

spring.datasource.username=visitor_service_user

spring.datasource.password=xD3FyxrpfMRwCKTeIwnQvv9h8xCHCMm7


# HikariCP settings
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

upload.file.max.size = 5242880
storage.file.path = filePath=/
Users/Documents/EVisitorFile/%YYYY%MM%/%LOGIND%/%DD%/

jwt.secret=hyKf4fK4Vt+uR0vJH7fYQx1aL9eP0Zg1QmN5vJ9jT2YkXb8Lw3rFd6Wp9Nc2Hv5ZaB3KqR8uPx4Lm7YnV1Es0cQ==
jwt.secret.expiration=86400000

encrypted.key=I7mX4pQ2nV7rT8aL5cFwY1hJ6uNz3NgY
